routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Master\BankController;
use App\Http\Controllers\Master\KategoriController;
use App\Http\Controllers\Master\BarangController;
use App\Http\Controllers\Master\VendorController;
use App\Http\Controllers\TransaksiController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('home');
})->name('home');

// ======= MASTER ===========
Route::group(['prefix' => '/master', 'as' => 'master.'], function () {
    Route::group(['prefix' => '/bank', 'as' => 'bank.'], function () {
        Route::get('/', [BankController::class, 'index'])->name('index');
        Route::post('/store', [BankController::class, 'store'])->name('store');
        Route::put('/update/{id}', [BankController::class, 'update'])->name('update');
        Route::delete('/destroy/{id}', [BankController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => '/kategori', 'as' => 'kategori.'], function () {
        Route::get('/', [KategoriController::class, 'index'])->name('index');
        Route::post('/store', [KategoriController::class, 'store'])->name('store');
        Route::put('/update/{id}', [KategoriController::class, 'update'])->name('update');
        Route::delete('/destroy/{id}', [KategoriController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => '/barang', 'as' => 'barang.'], function () {
        Route::get('/', [BarangController::class, 'index'])->name('index');
        Route::post('/store', [BarangController::class, 'store'])->name('store');
        Route::put('/update/{id}', [BarangController::class, 'update'])->name('update');
        Route::delete('/destroy/{id}', [BarangController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => '/vendor', 'as' => 'vendor.'], function () {
        Route::get('/', [VendorController::class, 'index'])->name('index');
        Route::post('/store', [VendorController::class, 'store'])->name('store');
        Route::put('/update/{id}', [VendorController::class, 'update'])->name('update');
        Route::delete('/destroy/{id}', [VendorController::class, 'destroy'])->name('destroy');
    });
});

Route::group(['prefix' => '/transaksi', 'as' => 'transaksi.'], function () {
    Route::get('/', [TransaksiController::class, 'index'])->name('index');
    Route::get('/create', [TransaksiController::class, 'create'])->name('create');
    Route::post('/store', [TransaksiController::class, 'store'])->name('store');
    Route::delete('/destroy/{id}', [TransaksiController::class, 'destroy'])->name('destroy');
    Route::get('/cek-limit/{id}', [TransaksiController::class, 'cekLimit'])->name('cekLimit');
});

resources/views/layouts/footer.blade.php
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Qotrunnada 2024</span>
        </div>
    </div>
</footer>

resources/views/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Procurementrangers</title>
    <link href="{{ asset('template/vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="{{ asset('template/css/sb-admin-2.min.css') }}" rel="stylesheet">
    <link href="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('plugins/sweetalert2/sweetalert2.min.css') }}" />
    <script src=" https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="{{ asset('plugins/sweetalert2/sweetalert2.all.min.js') }}"></script>
</head>

<body id="page-top">
    <div id="wrapper">
        @include('layouts.sidebar')
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                @include('layouts.topbar')
                <div class="container-fluid">
                    @include('sweetalert::alert')
                    @yield('content')
                </div>
            </div>
            @include('layouts.footer')
        </div>
    </div>
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    @include('layouts.script')
    @yield('script')
</body>

</html>

resources/views/layouts/script.blade.php
<script src="{{ asset('template/vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ asset('template/vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<script src="{{ asset('template/vendor/jquery-easing/jquery.easing.min.js') }}"></script>
<script src="{{ asset('template/js/sb-admin-2.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('template/vendor/datatables/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('template/js/demo/datatables-demo.js') }}"></script>
<script src="{{ asset('plugins/inputmask/min/jquery.inputmask.bundle.min.js')  }}"></script>
<script src="{{ asset('template/js/helpers/main.js') }}"></script>

resources/views/layouts/sidebar.blade.php
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">PROCUREMENT</div>
    </a>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('home') }}"">
            <i class=" fa fa-home"></i>
            <span>Home</span></a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Data Master
    </div>
    <li class="nav-item {{ Request::is('master/bank*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('master.bank.index') }}">
            <i class="fa fa-money-check"></i>
            <span>Bank</span></a>
    </li>
    <li class="nav-item {{ Request::is('master/kategori*') ? 'active' : '' }}">
        <a class=" nav-link" href="{{ route('master.kategori.index') }}">
            <i class="fa fa-th-list"></i>
            <span>Kategori Barang</span></a>
    </li>
    <li class="nav-item {{ Request::is('master/barang*') ? 'active' : '' }}">
        <a class=" nav-link" href="{{ route('master.barang.index') }}">
            <i class="fa fa-boxes"></i>
            <span>Barang</span></a>
    </li>
    <li class="nav-item {{ Request::is('master/vendor*') ? 'active' : '' }}">
        <a class=" nav-link" href="{{ route('master.vendor.index') }}">
            <i class="fa fa-store"></i>
            <span>Vendor</span></a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
        Transaksi
    </div>

    <li class="nav-item {{ Request::is('transaksi*') ? 'active' : '' }}">
        <a class="nav-link" href="{{ route('transaksi.index') }}">
            <i class=" fa fa-shopping-cart"></i>
            <span>Order Transaksi</span></a>
    </li>
    <hr class="sidebar-divider d-none d-md-block">
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

</ul>

resources/views/layouts/topbar.blade.php
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Qotrunnada Oktiriani</span>
                <img class="img-profile rounded-circle" src="{{ asset('template/img/undraw_profile.svg') }}">
            </a>
        </li>
    </ul>
</nav>